application: genewikitools
version: 1
runtime: python
api_version: 1

handlers:
- url: /ExtractReferences
  script: ExtractReferences.py

- url: /ListPages
  script: ListPages.py

- url: /RefreshPageList
  script: RefreshPageList.py

- url: /Pubmed2Mesh
  script: Pubmed2Mesh.py

- url: /ReadGeneWikiPage
  script: ReadGeneWikiPage.py

- url: /ReferenceReport
  script: ReferenceReport.py

- url: .*
  script: PrintDoc.py
