application: genewikitools
version: 1
runtime: python
api_version: 1

handlers:
- url: /ListPages
  script: ListPages.py

- url: /DataStoreTest
  script: DataStoreTest.py

- url: /RefreshPageList
  script: RefreshPageList.py

- url: .*
  script: PrintDoc.py
