application: genewikitools
version: 1
runtime: python
api_version: 1

handlers:
- url: /ListPages
  script: ListPages.py

- url: /RefreshPageList
  script: RefreshPageList.py

- url: /Pubmed2Mesh
  script: Pubmed2Mesh.py

- url: .*
  script: PrintDoc.py
