application: genewikitools
version: 1
runtime: python
api_version: 1

handlers:

### Main tools

- url: /ListPages
  script: ListPages.py

- url: /ReferenceReport
  script: ReferenceReport.py

### Helper tools

- url: /ExtractReferences
  script: ExtractReferences.py

- url: /Pubmed2Mesh
  script: Pubmed2Mesh.py

- url: /ReadGeneWikiPage
  script: ReadGeneWikiPage.py

- url: /RefreshPageList
  script: RefreshPageList.py


### Test scripts below
- url: /EnvironmentVariablesTest
  script: EnvironmentVariablesTest.py

- url: /GetGAEIpAddress
  script: GetGAEIpAddress.py

- url: /PostTest
  script: PostTest.py

- url: .*
  script: PrintDoc.py
