package org.genewiki.parse;


import org.genewiki.GWRevision;
import org.gnf.wikiapi.AbstractXMLParser;
import org.gnf.wikiapi.Page;
import org.gnf.wikiapi.Revision;

import java.util.ArrayList;
import java.util.List;

import org.xml.sax.Attributes;
import org.xml.sax.SAXException;

/**
 * Reads <code>Page</code> data from an XML file generated by the <a href="http://meta.wikimedia.org/w/api.php">Wikimedia API</a>
 * READS data from a call for category members
 * Code based on <code>XMLPagesParser</code>
 */
public class XMLDiffParser extends AbstractXMLParser {
//    
    private static final String REVISIONS = "revisions";
    
    private static final String REV = "rev";
    
    private static final String REV_ID = "revid";
    
    private static final String PARENT_ID = "parentid";
    
    private static final String COMMENT_ID = "comment";
    
    private static final String MINOR = "minor";
    
    private static final String USER = "user";
    
    private static final String TIMESTAMP = "timestamp";
    
    private static final String SIZE = "size";

    private static final String DIFF = "diff";
    
    private static final String FROM = "from";
    
    private static final String TO = "to";
    
	private GWRevision fRev;

	private List<GWRevision> revsList;
	
	private String diff;
	
	private String cmcontinue;

	public XMLDiffParser(String xmlText) throws SAXException {
		super(xmlText);
		revsList = new ArrayList<GWRevision>();
	}

	@Override
	public void startElement(String namespaceURI, String localName, String qName, Attributes atts) {
		fAttributes = atts;

		if((DIFF.equals(qName))){
			
		}
		else if(REVISIONS.equals(qName)){
			
		}
		fData = null;
	}

	public String getCmcontinue() {
		return cmcontinue;
	}

	public void setCmcontinue(String cmcontinue) {
		this.cmcontinue = cmcontinue;
	}

	@Override
	public void endElement(String uri, String name, String qName) {
		try {
			if (DIFF.equals(qName)) {
				diff = getString();
			}
			fData = null;
			fAttributes = null;
		} catch (RuntimeException re) {
			re.printStackTrace();
		}
	}

	public String getDiff() {
		return diff;
	}

	public void setDiff(String diff) {
		this.diff = diff;
	}


}
