package org.genewiki.parse;


import org.gnf.wikiapi.AbstractXMLParser;
import org.gnf.wikiapi.Page;

import java.util.ArrayList;
import java.util.List;

import org.xml.sax.Attributes;
import org.xml.sax.SAXException;

/**
 * Reads watchlist data from an XML file generated by the <a href="http://meta.wikimedia.org/w/api.php">Wikimedia API</a>
 * Response looks like

<?xml version="1.0"?>
<api>
<query>
<embeddedin>
<ei pageid="7120" ns="0" title="Calreticulin" />
<ei pageid="14895" ns="0" title="Insulin" />
</embeddedin></query><query-continue>
<embeddedin eicontinue="10|GNF_Protein_box|24762" />
</query-continue></api>

//<?xml version="1.0"?>
 * <api>
 * <watchlistraw>
 * <wr ns="0" title="Cyclin-dependent kinase 2" /></watchlistraw></api>\n


 * Code based on <code>XMLPagesParser</code>
 */
public class XMLWatchlistParser extends AbstractXMLParser {
	private static final String CATEGORY_TAG1 = "wr";
	
	private static final String CATEGORY_MEMBERS = "watchlistraw";

	private static final String NS_ID = "ns";

	private static final String TITLE_ID = "title";

	private Page fPage;

	private List<Page> pagesList;
	
	private String wrcontinue;

	public XMLWatchlistParser(String xmlText) throws SAXException {
		super(xmlText);
		pagesList = new ArrayList<Page>();
	}

	@Override
	public void startElement(String namespaceURI, String localName, String qName, Attributes atts) {
		fAttributes = atts;
//		System.out.println("--"+qName+"--");
		if (CATEGORY_TAG1.equals(qName)){
			fPage = new Page();
			fPage.setNs(fAttributes.getValue(NS_ID));
			fPage.setTitle(fAttributes.getValue(TITLE_ID));
		}else if(CATEGORY_MEMBERS.equals(qName)){
			if(fAttributes.getValue("wrcontinue")!=null){
				setWrcontinue(fAttributes.getValue("wrcontinue"));
			}
		}
		fData = null;
	}

	public String getWrcontinue() {
		return wrcontinue;
	}

	public void setWrcontinue(String cmcontinue) {
		this.wrcontinue = cmcontinue;
	}

	@Override
	public void endElement(String uri, String name, String qName) {
		try {
			if (CATEGORY_TAG1.equals(qName)) {
				if (fPage != null) {
					pagesList.add(fPage);
				}
				// System.out.println(getString());
			}

			fData = null;
			fAttributes = null;

		} catch (RuntimeException re) {
			re.printStackTrace();
		}
	}

	public List<Page> getPagesList() {
		return pagesList;
	}

}
